file = LOAD 'Users.csv' Using PigStorage(',') AS (ID:int, Reputation:int, CreationDate:chararray, DisplayName:chararray, lastAccessDate:chararray, views:int, upvote:int, downvote:int, accountId:int);
generated = FOREACH file GENERATE Reputation, DisplayName;
ordered_value = ORDER generated BY Reputation DESC;
limited = LIMIT ordered_value 100;
STORE limited INTO '/pigresults/most_Valuable_User' USING PigStorage(',');
