-- mostViewedUsers
loaded = LOAD 'hdfs://Shrini:9000/stackexchange/Users.txt' Using PigStorage() AS (userId:int, reputation:int, creationDate:chararray, displayName:chararray, lastAccessDate:chararray, views:int, upvote:int, downvote:int, accountId:int);
generated = FOREACH loaded GENERATE views, displayName;
ordered = ORDER generated BY views DESC;
limited = LIMIT ordered 100;
STORE limited INTO '/pigresults/mostViewedUsers';
