file = LOAD 'Users.csv' Using PigStorage(',') AS (ID:int, Reputation:int, CreationDate:chararray, DisplayName:chararray, lastAccessDate:chararray, WebsiteUrl:chararray, Location:chararray, AboutMe:chararray, views:int, upvote:int, downvote:int, ProfileImageUrl:chararray,email:chararray,accountId:int);
query_filtered = FILTER file BY NOT(lastAccessDate MATCHES '^40997844.*');
generated = FOREACH query_filtered GENERATE Reputation, ID;
ordered_value = ORDER generated BY Reputation DESC;
limited = LIMIT ordered_value 100;
STORE limited INTO '/pigresults/most_Valuable_User' USING PigStorage(',');
